# Generated by Django 5.0.4 on 2024-05-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
